<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Keeper\KeeperBaseLib\KeeperBaseLib\KeeperBaseLib.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="com.rlabrecque.steamworks.net">
      <HintPath>C:\Program Files (x86)\Steam\steamapps\common\RimWorld\RimWorldWin64_Data\Managed\com.rlabrecque.steamworks.net.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
