<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<Platforms>AnyCPU;x64</Platforms>
		<LangVersion>preview</LangVersion>

	    <Product>RimKeeperModOrganizer</Product>
	    <Authors>Keepercraft</Authors>
	    <Company>$(Authors)</Company>
	    <Copyright>Copyright © $([System.DateTime]::UtcNow.ToString('yyyy')) $(Authors) Contains third-party components.</Copyright>
	    <Description>Rimkeeper Apache-2.0 license</Description>
	    <RepositoryUrl>https://github.com/keepercraft/RimKeeperModOrganizer</RepositoryUrl>

	    <ProjectName>RimKeeperModOrganizer</ProjectName>
		<AssemblyName>$(ProjectName)</AssemblyName>	
	    <NeutralLanguage>pl-PL</NeutralLanguage>
	    <SupportedCultures>pl-PL;en-US</SupportedCultures>    
	  
		<Major>0</Major>
		<Minor>3</Minor>
		<Build>15</Build>
		<RawSeconds>$([System.DateTime]::UtcNow.TimeOfDay.TotalSeconds)</RawSeconds>
		<ComputedRevision>$([System.Convert]::ToInt32($([MSBuild]::Divide($(RawSeconds), 2))))</ComputedRevision>
		<Timestamp>$([System.DateTime]::UtcNow.ToString("yyyyMMdd-HHmm"))</Timestamp>
		<Version>$(Major).$(Minor).$(Build)-alpha.$(Timestamp)</Version>
		<FileVersion>$(Major).$(Minor).$(Build).$(ComputedRevision)</FileVersion>
		<AssemblyVersion>$(Major).$(Minor).$(Build).0</AssemblyVersion>  
  </PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<DebugType>none</DebugType>
		<DebugSymbols>false</DebugSymbols>
		<CopyOutputSymbolsToPublishDirectory>false</CopyOutputSymbolsToPublishDirectory>
		<AllowedReferenceRelatedFileExtensions>none</AllowedReferenceRelatedFileExtensions>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
		<DebugType>none</DebugType>
		<DebugSymbols>false</DebugSymbols>
		<CopyOutputSymbolsToPublishDirectory>false</CopyOutputSymbolsToPublishDirectory>
		<AllowedReferenceRelatedFileExtensions>none</AllowedReferenceRelatedFileExtensions>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="AssemblyInfo.cs" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="AssemblyInfo.cs" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Keepercraft_DEV.cer" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\Keeper\KeeperBaseLib\KeeperBaseLib\KeeperBaseLib.csproj" />
		<ProjectReference Include="..\KeeperDataGrid\KeeperDataGrid.csproj" />
		<ProjectReference Include="..\RimKeeperModOrganizerLib\RimKeeperModOrganizerLib.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Themes\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="gong-wpf-dragdrop" Version="4.0.0" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.2" />
		<PackageReference Include="PixiEditor.ColorPicker" Version="3.4.2.2" />
		<PackageReference Include="Sdl.MultiSelectComboBox" Version="1.0.103" />
	</ItemGroup>

	<Target Name="CustomPostPublishActions" AfterTargets="Publish">
		<PropertyGroup>
			<SignToolPath>C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64\signtool.exe</SignToolPath>
			<AbsPublishDir>$([System.IO.Path]::GetFullPath('$(ProjectDir)$(PublishDir)'))</AbsPublishDir>
			<CertThumbprint>b681faf16773ed5d16b6811fceedbbecb5ed85b8</CertThumbprint>
			<CertFolder>K:\Programing\Certificates</CertFolder>
			<CerFile>$(CertFolder)\Keepercraft_DEV.cer</CerFile>
		</PropertyGroup>

		<Message Importance="high" Text="--- PODPISYWANIE PRZY UŻYCIU THUMBPRINT ---" />
		<Exec Command="powershell -Command &quot;for ($i=1; $i -le 5; $i++) { try { &amp; '$(SignToolPath)' sign /sha1 $(CertThumbprint) /fd SHA256 /t http://timestamp.digicert.com '$(AbsPublishDir)*.exe'; Write-Host 'Sukces!'; break } catch { Write-Host 'Plik zablokowany, próba $i/5...'; Start-Sleep -Seconds 2 } }&quot;" />

		<Copy SourceFiles="$(AbsPublishDir)$(TargetName).exe"
			DestinationFiles="$(AbsPublishDir)$(TargetName)_$(FileVersion).exe"
			SkipUnchangedFiles="false" />
		
		<Message Importance="high" Text="--- PUBLIKACJA ZAKOŃCZONA ---" />
	</Target>

	<!--<Target Name="GenerateLicensesOnBuild" BeforeTargets="BeforeBuild">
		<Message Importance="high" Text="Generowanie licencji do pliku THIRD-PARTY-NOTICES.txt..." />
		<Exec Command="dotnet tool run dotnet-project-licenses -i . -u -o -e -;-outfile ..\THIRD-PARTY-NOTICES.txt -;-manual-package-information ..\manual-packages.json " />
		<ItemGroup>
			<None Include="THIRD-PARTY-NOTICES.txt">
				<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
			</None>
		</ItemGroup>
	</Target-->
	
	<Target Name="CopyLicenses" AfterTargets="Publish">
		<Copy SourceFiles="..\LICENSE"
			  DestinationFolder="$(PublishDir)"
			  SkipUnchangedFiles="true" />
		<ItemGroup>
			<LicenseFiles Include="..\Licenses\**\*.*" />
		</ItemGroup>
		<Copy SourceFiles="@(LicenseFiles)"
				  DestinationFolder="$(PublishDir)Licenses\%(RecursiveDir)"
				  SkipUnchangedFiles="true" />
		<Message Importance="high" Text="--- LICENSE COPY COMPLETED ---" />
	</Target>
	
</Project>
